### ISSUE TITLE
Error xampp even create landing( save image on local directory landing file) 

### ISSUE THREAD

**Issue by nabillaputrimaharani** [xamppsul/sisarpas#30]
Could not move the file "C:\xampp\tmp\phpECB2.tmp" to "sisarpas/assets/landingFile\2024-03-12 10:34:03_Screenshot (10).png" (move_uploaded_file(): Unable to move &quot;C:\xampp\tmp\phpECB2.tmp&quot; to &quot;sisarpas/assets/landingFile\2024-03-12 10:34:03_Screenshot (10).png&quot;).

**Comment by xamppsul** [comment]
solution
1. remove xampp change to laragon
2. permission change become full access (777)
3. nama file kepanjangan kasih short

**Comment by xamppsul** [comment]
@nabillaputrimaharani sudah di ubah permission jadi full kah ? (777)
