### ISSUE TITLE
Config Mailer With SMTP Sendinblue

### ISSUE THREAD

**Issue by xamppsul** [xamppsul/sisarpas#78]
current:

`MAIL_MAILER=smtp
MAIL_HOST=smtp.mailersend.net
MAIL_PORT=587
MAIL_USERNAME=MS_gZUAjy@trial-pq3enl6y1q8g2vwr.mlsender.net
MAIL_PASSWORD=8IvTH3L4a0rRYqpT
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS=sarpras@gmail.com
MAIL_FROM_NAME="Sarpras ITERA"
`
goals: 

`MAIL_MAILER=smtp
MAIL_HOST=smtp-relay.brevo.com
MAIL_PORT=587
MAIL_USERNAME=nabilla.120140177@student.itera.ac.id
MAIL_PASSWORD=4vSMLCDqkQXHVKOm
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS="nabilla.120140177@student.itera.ac.id"
MAIL_FROM_NAME="Sarpras ITERA"`

**Comment by xamppsul** [comment]
@nabillaputrimaharani saya sudah open issue terkait ini yah nanti kalo misalnya ada kendala langsung comment di issue ini aja oke

**Comment by nabillaputrimaharani** [comment]
@syamsulapp sendinblue has blocked your account because, your account not comply of requirements account

**Comment by xamppsul** [comment]
@nabillaputrimaharani i have been reactive account then register again and result is good, account is valid and mail account work on smtp
