### ISSUE TITLE
Status barang tidak bisa dirubah kalo ID barangnya belum diubah

### ISSUE THREAD

**Issue by nabillaputrimaharani** [xamppsul/sisarpas#92]
Waktu mau edit status barang dari ready ke maintenance atau not ready dibagia kode barangnya harus diubah dulu baru bisa ke ganti statusnya. Jadi kalo Id nya dirubah dia malah tambah barang jadinya
![Screenshot (156)](https://github.com/syamsulapp/sisarpas/assets/105861936/52576b1a-3bfb-4bcf-bc8a-e6f9ed3380e6)

**Comment by xamppsul** [comment]
@nabillaputrimaharani done yah mbak
