### ISSUE TITLE
Hide Menu Dashboard Admin

### ISSUE THREAD

**Issue by nabillaputrimaharani** [xamppsul/sisarpas#96]
Menu log error dan Log success di dashboard admin di hide dulu
![image](https://github.com/syamsulapp/sisarpas/assets/105861936/b0afa051-9a19-48c5-a374-eb55b99a9455)

**Comment by xamppsul** [comment]
@nabillaputrimaharani jangan di hide mbak supaya ngetracking errornya bisa lebih mudah
